"use client";

import { useMemo, useRef, useState } from "react";
import type { LevelModule, LevelProps } from "@/engine/types";
import { CouplingGraph, type ControlState } from "@/engine/coupling/graph";
import { scrambleFrom } from "@/engine/coupling/solver";
import { SlopBadge, SlopCard, SlopCta, SlopError, SlopFooter, SlopHeading, SlopHint, SlopMicrocopy } from "@/ui/slop/Slop";
import { FOOTER_LINKS, slopSubhead } from "@/ui/slop/phrases";
import s from "./styles.module.css";

const TARGET_DIGITS = [4, 7, 2, 9] as const;
const IDS = ["d0", "d1", "d2", "d3"] as const;
const TARGET: ControlState = Object.fromEntries(IDS.map((id, i) => [id, TARGET_DIGITS[i]!]));
/** Pixels of drag per notch. */
const NOTCH = 18;

/**
 * The gear train.
 *
 * Four brass dials. Turning one turns every dial to its right — so the honest
 * solve is strictly left to right, where each placement is final because the
 * dials it disturbs are the ones you have not set yet. Roughly twelve seconds
 * to realise and eight to execute.
 *
 * The coupling is not hand-rolled here: it is the shared graph engine that
 * eleven more levels will use in Phase 5, and the start state is generated by
 * walking legal moves back from the solved state rather than by shuffling —
 * which is what makes every seed provably reachable.
 */
function Component({ onSolve, onFail, rng, sfx }: LevelProps) {
  const graph = useMemo(
    () =>
      new CouplingGraph(
        IDS.map((id) => ({ id, min: 0, max: 9, wrap: true })),
        [
          { from: "d0", to: "d1", kind: "propagate", ratio: 1 },
          { from: "d1", to: "d2", kind: "propagate", ratio: 1 },
          { from: "d2", to: "d3", kind: "propagate", ratio: 1 },
        ],
      ),
    [],
  );

  const seed = () => {
    let start = scrambleFrom(graph, TARGET, 6, rng);
    /* Never hand the player a free thousand points. */
    if (IDS.every((id) => start[id] === TARGET[id])) start = graph.apply(start, "d0", 3);
    return start;
  };

  const [state, setState] = useState<ControlState>(seed);
  const [error, setError] = useState<string | null>(null);
  const [sub] = useState(() => slopSubhead(rng));
  const drag = useRef<{ index: number; y: number; carry: number } | null>(null);

  const turn = (index: number, delta: number) => {
    if (!delta) return;
    setState((prev) => graph.apply(prev, IDS[index]!, delta));
    sfx.click();
  };

  const onPointerDown = (e: React.PointerEvent, index: number) => {
    e.preventDefault();
    (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
    drag.current = { index, y: e.clientY, carry: 0 };
  };

  const onPointerMove = (e: React.PointerEvent) => {
    const d = drag.current;
    if (!d) return;
    e.preventDefault();
    d.carry += d.y - e.clientY; // drag up increments
    d.y = e.clientY;
    while (Math.abs(d.carry) >= NOTCH) {
      const step = d.carry > 0 ? 1 : -1;
      d.carry -= step * NOTCH;
      turn(d.index, step);
    }
  };

  const onPointerUp = () => {
    drag.current = null;
  };

  const confirm = () => {
    if (IDS.every((id) => state[id] === TARGET[id])) {
      onSolve();
      return;
    }
    setError("Incorrect. For your security, the dials have been re-seeded. 🔒");
    setState(seed());
    onFail("wrong-pin");
    sfx.fail();
  };

  return (
    <SlopCard>
      <SlopBadge>Security · SOC2 (pending)</SlopBadge>
      <SlopHeading>Set Your Security PIN 🔒</SlopHeading>
      <SlopMicrocopy>{sub}</SlopMicrocopy>

      <div className={s.target}>{TARGET_DIGITS.join("")}</div>

      <div className={s.dials}>
        {IDS.map((id, i) => {
          const v = state[id]!;
          return (
            <div key={id} className={s.dial}>
              <div
                className={`${s.body} ${v === TARGET[id] ? s.settled : ""}`}
                tabIndex={0}
                role="spinbutton"
                aria-label={`Dial ${i + 1}`}
                aria-valuenow={v}
                aria-valuemin={0}
                aria-valuemax={9}
                onPointerDown={(e) => onPointerDown(e, i)}
                onPointerMove={onPointerMove}
                onPointerUp={onPointerUp}
                onPointerCancel={onPointerUp}
                onKeyDown={(e) => {
                  if (e.key === "ArrowUp") { e.preventDefault(); turn(i, 1); }
                  else if (e.key === "ArrowDown") { e.preventDefault(); turn(i, -1); }
                }}
              >
                <div className={s.reel}>
                  <div className={s.n}>{(v + 9) % 10}</div>
                  <div className={s.n}>{v}</div>
                  <div className={s.n}>{(v + 1) % 10}</div>
                </div>
                <div className={s.shade} />
                <div className={s.window} />
              </div>
              <div className={s.steps}>
                <button type="button" onClick={() => turn(i, -1)} aria-label={`Dial ${i + 1} down`}>−</button>
                <button type="button" onClick={() => turn(i, 1)} aria-label={`Dial ${i + 1} up`}>+</button>
              </div>
              <div className={s.label}>DIAL {i + 1}</div>
            </div>
          );
        })}
      </div>

      <SlopCta onClick={confirm}>Confirm PIN</SlopCta>
      <SlopError>{error}</SlopError>
      <SlopHint>
        Drag a dial or use + / − to turn it. The dials are precision-machined and interlock for
        extra security. 🔧
      </SlopHint>
      <SlopFooter links={FOOTER_LINKS} />
    </SlopCard>
  );
}

export const L37: LevelModule = {
  meta: {
    id: "L37",
    slug: "set-your-security-pin",
    title: "Set Your Security PIN",
    tier: "cursed",
    family: "coupled",
    parSeconds: 30,
    requires: ["pointer"],
    incompatibleModifiers: ["slippery"],
  },
  Component,
};
