import { ImageResponse } from "next/og";

/**
 * The share card.
 *
 * Every post carries the personal detail in its text — the score, the level
 * that killed them. The card's job is to make a stranger scrolling past
 * understand what they are looking at in under a second, so it leads with the
 * premise rather than with a number.
 */
export function GET() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "#0B0E13",
          padding: "64px 72px",
          fontFamily: "sans-serif",
        }}
      >
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ fontSize: 148, fontWeight: 900, letterSpacing: "-0.05em", lineHeight: 0.85, color: "#E9EEF4", display: "flex" }}>
            AI
          </div>
          <div style={{ fontSize: 148, fontWeight: 900, letterSpacing: "-0.05em", lineHeight: 0.85, color: "#FF4A2B", display: "flex" }}>
            RUSH
          </div>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
          <div style={{ fontSize: 40, color: "#E9EEF4", lineHeight: 1.25, maxWidth: 900, display: "flex" }}>
            Five minutes of interfaces generated by something that has seen a million forms and understood none of them.
          </div>
          <div style={{ fontSize: 27, color: "#8593A5", display: "flex" }}>
            Solve or skip. The clock does not stop either way.
          </div>
        </div>

        <div style={{ display: "flex", gap: 14 }}>
          {["5:00 RUN", "SIX LEVELS", "ONE LEADERBOARD"].map((t) => (
            <div
              key={t}
              style={{
                display: "flex", fontSize: 21, letterSpacing: "0.14em", color: "#8593A5",
                border: "1px solid #232B37", borderRadius: 6, padding: "10px 18px",
              }}
            >
              {t}
            </div>
          ))}
        </div>
      </div>
    ),
    { width: 1200, height: 675 },
  );
}
