"use client";

import { useState } from "react";
import type { LevelModule, LevelProps } from "@/engine/types";
import { meta } from "./meta";
import { SlopBadge, SlopCard, SlopFooter, SlopHeading, SlopHint, SlopMicrocopy } from "@/ui/slop/Slop";
import { FOOTER_LINKS, slopSubhead } from "@/ui/slop/phrases";
import { PAIRS, PARASITE, applyMove, same, scramble } from "./puzzle";
import s from "./styles.module.css";

const ITEMS = ["Security", "Performance", "Reliability", "Cost", "Delight"] as const;
const SCRAMBLE_MOVES = 5;

/**
 * Five priorities, drag to reorder, target order shown alongside.
 *
 * Every move you make also swaps two other items. You are not sorting a list —
 * you are solving a permutation puzzle with a fixed generator set, and the
 * thing that makes it click is realising that the parasitic swap is
 * deterministic rather than random. It always takes the same pair. Once you
 * see which one, the list stops being chaos and becomes arithmetic.
 *
 * No fail state, and a Reset that returns to the seeded start. Wandering is a
 * real risk in a puzzle like this and using Reset is often correct; punishing
 * either would make it tedious rather than cruel, which is the wrong side of
 * the line.
 *
 * Solvability is proved by construction rather than hoped for — see
 * `puzzle.ts`. Every move is its own inverse, and the start is generated by
 * walking legal moves back from the target.
 */
function Component({ onSolve, rng, sfx }: LevelProps) {
  const [target] = useState<string[]>(() => rng.shuffle([...ITEMS]));
  const [start] = useState<string[]>(() => scramble(target, SCRAMBLE_MOVES, rng));
  const [order, setOrder] = useState<string[]>(start);
  const [moves, setMoves] = useState(0);
  const [sub] = useState(() => slopSubhead(rng));
  const [done, setDone] = useState(false);

  const move = (k: number) => {
    if (done) return;
    const next = applyMove(order, k);
    setOrder(next);
    setMoves((n) => n + 1);
    sfx.pick(k);
    if (same(next, target)) {
      setDone(true);
      sfx.solve();
      onSolve();
    }
  };

  const reset = () => {
    setOrder(start);
    setMoves(0);
    sfx.thud();
  };

  return (
    <SlopCard>
      <SlopBadge>Onboarding · AI-Powered</SlopBadge>
      <SlopHeading>Rank what matters to your team 📊</SlopHeading>
      <SlopMicrocopy>{sub}</SlopMicrocopy>

      <div className={s.wrap}>
        <div className={s.col}>
          <div className={s.colHead}>Your ranking</div>
          <ol className={s.list}>
            {order.map((item, i) => (
              <li
                key={item}
                className={`${s.row} ${item === target[i] ? s.rowOk : ""}`}
                data-position={i}
                data-item={item}
              >
                <span className={s.rank}>{i + 1}</span>
                <span className={s.name}>{item}</span>
                <span className={s.moves}>
                  <button
                    type="button"
                    className={s.arrow}
                    aria-label={`Move ${item} up`}
                    disabled={i === 0}
                    onClick={() => move(i - 1)}
                  >
                    ↑
                  </button>
                  <button
                    type="button"
                    className={s.arrow}
                    aria-label={`Move ${item} down`}
                    disabled={i === PAIRS.length}
                    onClick={() => move(i)}
                  >
                    ↓
                  </button>
                </span>
              </li>
            ))}
          </ol>
        </div>

        <div className={s.col}>
          <div className={s.colHead}>Recommended</div>
          <ol className={`${s.list} ${s.ghostList}`}>
            {target.map((item, i) => (
              <li className={s.ghostRow} key={item} data-target={i}>
                <span className={s.rank}>{i + 1}</span>
                <span className={s.name}>{item}</span>
              </li>
            ))}
          </ol>
        </div>
      </div>

      <div className={s.bar}>
        <span className={s.count}>{moves} moves</span>
        <button type="button" className={s.reset} onClick={reset}>
          Reset
        </button>
      </div>

      <SlopHint>
        Our model has pre-ranked these based on teams like yours. Adjusting one priority may
        rebalance the others to preserve overall alignment. ⚖️
      </SlopHint>
      <SlopFooter links={FOOTER_LINKS} />
    </SlopCard>
  );
}

export const L41: LevelModule = { meta, Component };
export { PAIRS, PARASITE };
