import type { Metadata, Viewport } from "next";
import { Archivo_Black, Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter", display: "swap" });
const mono = JetBrains_Mono({ subsets: ["latin"], variable: "--font-jetbrains", display: "swap" });

/**
 * The chrome's display face.
 *
 * Deliberately not Inter at weight 800. That combination — tight tracking, a
 * violet gradient, a lot of air — is the house style of every interface this
 * game is making fun of, and wearing it on the front page would be the one
 * joke the player is not in on. Archivo Black is a printed-poster face: heavy,
 * a bit blunt, obviously chosen by a person.
 */
const display = Archivo_Black({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-archivo",
  display: "swap",
});

const DESCRIPTION =
  "Five minutes of interfaces generated by something that has seen a million forms and understood none of them. Solve or skip \u2014 the clock does not stop either way.";

/**
 * Where the share card actually lives.
 *
 * `metadataBase` is what absolute-ises og:image, and getting it wrong is
 * invisible locally and fatal in production — X fetches the URL from the page,
 * so a localhost base means every shared card silently fails to render.
 * `VERCEL_PROJECT_PRODUCTION_URL` is set automatically on every deployment, so
 * this needs no configuration; the explicit override is there for a custom
 * domain later.
 */
function siteUrl(): string {
  if (process.env.NEXT_PUBLIC_SITE_URL) return process.env.NEXT_PUBLIC_SITE_URL;
  if (process.env.VERCEL_PROJECT_PRODUCTION_URL) {
    return `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`;
  }
  return "http://localhost:3000";
}

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl()),
  title: { default: "AI Rush", template: "%s \u00b7 AI Rush" },
  description: DESCRIPTION,
  openGraph: {
    title: "AI Rush",
    description: DESCRIPTION,
    type: "website",
    images: [{ url: "/api/og", width: 1200, height: 675 }],
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Rush",
    description: DESCRIPTION,
    images: ["/api/og"],
  },
};

export const viewport: Viewport = {
  themeColor: "#0b0e13",
  width: "device-width",
  initialScale: 1,
  /* Levels put controls in the corners deliberately; they must not collide
     with a notch. Zoom stays enabled — one level's honest solve needs it. */
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${mono.variable} ${display.variable}`}>
      <body>{children}</body>
    </html>
  );
}
