import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter", display: "swap" });
const mono = JetBrains_Mono({ subsets: ["latin"], variable: "--font-jetbrains", display: "swap" });

const DESCRIPTION =
  "Five minutes of interfaces generated by something that has seen a million forms and understood none of them. Solve or skip \u2014 the clock does not stop either way.";

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000"),
  title: { default: "AI Rush", template: "%s \u00b7 AI Rush" },
  description: DESCRIPTION,
  openGraph: {
    title: "AI Rush",
    description: DESCRIPTION,
    type: "website",
    images: [{ url: "/api/og", width: 1200, height: 675 }],
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Rush",
    description: DESCRIPTION,
    images: ["/api/og"],
  },
};

export const viewport: Viewport = {
  themeColor: "#0b0e13",
  width: "device-width",
  initialScale: 1,
  /* Levels put controls in the corners deliberately; they must not collide
     with a notch. Zoom stays enabled — one level's honest solve needs it. */
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${mono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
