import type { MetadataRoute } from "next";

/**
 * The install.
 *
 * `ROADMAP.md` Phase 7 exits when this is on a home screen, fullscreen, with
 * no notch collisions and a wake lock that survives five minutes. This file is
 * the first of those four.
 *
 * Two choices worth stating:
 *
 * `display: "standalone"` rather than `"fullscreen"`. Fullscreen hides the
 * status bar, which means hiding the clock — and a game whose entire pressure
 * is a five-minute countdown should not also take away the player's ability to
 * see what time it is. The game's own clock is in the HUD; the phone's belongs
 * to them.
 *
 * `orientation: "portrait"`. Not a preference — six levels put controls in
 * fixed screen corners and one of them asks you to physically tilt the device,
 * which is a mechanic that stops meaning anything if the layout rotates
 * underneath it.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "AI Rush",
    short_name: "AI Rush",
    description:
      "Five minutes of interfaces generated by something that has seen a million forms and understood none of them.",
    start_url: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#0b0e13",
    theme_color: "#0b0e13",
    categories: ["games", "entertainment"],
    icons: [
      { src: "/api/icon?size=192", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/api/icon?size=512", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/api/icon?size=512&maskable=1",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    /*
     * Straight into a run, from the home screen.
     *
     * Both of these are the whole product in one tap — long-pressing the icon
     * and getting "Start a run" is the difference between an installed game and
     * a bookmark.
     */
    shortcuts: [
      { name: "Start a run", url: "/play", description: "Five minutes. No pause." },
      { name: "Practice", url: "/levels", description: "Any level, no clock, nothing filed." },
    ],
  };
}
