import Link from "next/link";
import { boardTop, liveStats } from "@/lib/db";
import { Handle } from "@/ui/Handle";
import { LiveDot } from "@/ui/LiveDot";
import s from "./page.module.css";

export const dynamic = "force-dynamic";

/**
 * The landing page, which is already a joke: START is red and on the right.
 *
 * The full green-Cancel/red-Continue dialog belongs to L01 and is not run
 * here — the same bit twice inside thirty seconds blunts both.
 *
 * Under it, the top of the board. A name and a number someone could beat is a
 * far better reason to press START than any amount of copy about the game.
 */
export default async function Home() {
  const [top, stats] = await Promise.all([boardTop(false, 5), liveStats()]);

  return (
    <main className={s.shell}>
      <div className={s.screen}>
        <h1 className={s.title}>
          AI<i>RUSH</i>
        </h1>
        <p className={s.lede}>
          Five minutes. A stack of interfaces generated by something that has seen a million
          forms and understood <strong>none of them</strong>. Solve or skip — the clock does not
          stop either way.
        </p>

        <LiveDot playingNow={stats.playingNow} runsToday={stats.runsToday} players={stats.players} />

        <div className={s.dialog}>
          <h2>Ready to get started? ✨</h2>
          <p>We just need a moment to verify a few things. This should be quick!</p>
          <div className={s.row}>
            <Link className={s.ghost} href="/play?mercy=1">
              Mercy mode
            </Link>
            <Link className={s.danger} href="/play">
              ⚠ START
            </Link>
          </div>
          <div className={s.note}>
            <strong>Mercy mode</strong> removes every level that needs a microphone, camera or
            motion, disables the four punishing modifiers, and files scores to a separate board.
            No mockery, no catch — it is the one part of this that is sincere.
          </div>
        </div>

        {top.length > 0 && (
          <div className={s.boardBlock}>
            <div className={s.boardHead}>
              <span>Survivors</span>
              <Link href="/board">full board →</Link>
            </div>
            <div className={s.mini}>
              {top.map((r) => (
                <Link
                  key={`${r.handle}-${r.rank}`}
                  className={s.miniRow}
                  href={
                    r.score > 0
                      ? { pathname: "/play", query: { seed: r.seed, vs: r.handle, target: r.score } }
                      : { pathname: "/play", query: { seed: r.seed } }
                  }
                >
                  <span className={s.miniRank}>#{r.rank}</span>
                  <Handle handle={r.handle} size={22} link={false} />
                  <span className={s.miniScore}>{r.score.toLocaleString()}</span>
                </Link>
              ))}
            </div>
            <p className={s.boardFoot}>Tap anyone to play their exact run and try to beat it.</p>
          </div>
        )}

        <p className={s.warn}>
          Contains flashing colour and sudden sound. Sound can be muted from the bar once a run
          starts.
        </p>
      </div>
    </main>
  );
}
