import Link from "next/link";
import s from "./page.module.css";

/**
 * The landing page, which is already a joke: START is red and on the right.
 *
 * The full green-Cancel/red-Continue dialog belongs to L01 and is not run
 * here — the same bit twice inside thirty seconds blunts both.
 */
export default function Home() {
  return (
    <main className={s.shell}>
      <div className={s.screen}>
        <h1 className={s.title}>
          AI<i>RUSH</i>
        </h1>
        <p className={s.lede}>
          Five minutes. A stack of interfaces generated by something that has seen a million
          forms and understood <strong>none of them</strong>. Solve or skip — the clock does not
          stop either way.
        </p>
        <p className={s.warn}>
          Contains flashing colour and sudden sound. Sound can be muted from the bar once a run
          starts.
        </p>

        <div className={s.dialog}>
          <h2>Ready to get started? ✨</h2>
          <p>We just need a moment to verify a few things. This should be quick!</p>
          <div className={s.row}>
            <Link className={`${s.row} ${s.ghost}`} href="/play?mercy=1">
              Mercy mode
            </Link>
            <Link className={s.danger} href="/play">
              ⚠ START
            </Link>
          </div>
          <div className={s.note}>
            <strong>Mercy mode</strong> removes every level that needs a microphone, camera or
            motion, disables the four punishing modifiers, and files scores to a separate board.
            No mockery, no catch — it is the one part of this that is sincere.
          </div>
        </div>
      </div>
    </main>
  );
}
